import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  preload: true,
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Wingman',
  description: 'Generated by Wingman',
  icons: {
    icon: '/logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${inter.variable} antialiased`}>
        <div className="flex h-screen">
          <Sidebar />
          <div className="flex-1 overflow-auto h-screen">
            <Header />
            <div className="mx-4 md:mx-10 rounded-[20px] shadow-section my-9 py-8 px-2 md:px-6">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
